export const loremIpsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ornare ut lectus eu convallis. Pellentesque eu vehicula augue. Aenean dignissim vehicula enim, sit amet scelerisque erat convallis eget. Suspendisse id finibus risus. Morbi dapibus eu metus vel malesuada. Phasellus quis mauris rhoncus, porta dolor vitae, pharetra massa. Quisque nisl enim, molestie nec scelerisque ac, ornare eget arcu. Fusce eget dignissim neque. Quisque at enim dignissim, imperdiet massa non, fringilla dolor. Fusce convallis ipsum vel dui fringilla, sit amet dictum dolor suscipit. Maecenas ut volutpat arcu. Nulla a dignissim erat, vel auctor massa. Donec nec metus ac turpis malesuada volutpat eu at ipsum. Praesent tortor sapien, euismod sed velit ut, accumsan tincidunt leo.

Praesent vel arcu commodo, placerat mauris vel, dignissim metus. Cras feugiat lacus ac ex porttitor, non fringilla tellus sagittis. Mauris at nibh eu magna laoreet viverra. In ultricies porta lorem, ac mattis eros mattis vel. Aenean feugiat condimentum dui eget accumsan. Duis consequat mattis lectus tempor lobortis. Suspendisse arcu ante, sagittis nec eleifend at, pellentesque nec nulla. Vivamus neque nulla, semper maximus blandit id, ultrices vel turpis.

Donec eget malesuada urna, at dignissim velit. Proin sit amet faucibus nisl. Aenean ornare aliquet est, quis varius risus vulputate eu. Nullam a enim blandit, semper massa ac, ultrices arcu. Etiam faucibus justo libero, euismod mattis mauris sollicitudin et. Aliquam blandit lectus tortor, eget fringilla velit tincidunt in. Curabitur consequat feugiat enim in porta.

Nam nunc nunc, tempus nec elit eget, finibus iaculis mi. Aenean fringilla sed nisl vel convallis. Cras eu nulla ut ex sollicitudin aliquam pellentesque at purus. In magna lectus, ultricies sit amet dui sit amet, ultricies vulputate ex. Praesent sodales risus sed massa faucibus iaculis. Mauris euismod dapibus quam at ultrices. Suspendisse pulvinar a nulla eget iaculis. Vivamus euismod tellus et sagittis fermentum. In rutrum efficitur neque sed bibendum. Mauris sed ex nulla. Mauris elit nulla, scelerisque in imperdiet nec, congue varius tellus. Sed a laoreet nibh, quis tristique lorem.

Sed maximus fringilla massa non fermentum. Nunc auctor urna et leo posuere iaculis. Donec ultricies, ante vel tincidunt placerat, neque metus pharetra orci, vitae elementum orci ligula nec ex. Nunc euismod convallis pharetra. Pellentesque leo velit, volutpat at auctor vel, malesuada nec sem. Pellentesque fermentum justo nec feugiat dapibus. Pellentesque vitae urna non ipsum ultrices mollis. Donec nec varius leo. Maecenas vehicula commodo velit id vulputate.

Vestibulum hendrerit sapien lacus, non laoreet metus pulvinar eget. In at odio quis nulla eleifend condimentum. Ut ac turpis mollis, consectetur ipsum vitae, viverra arcu. Suspendisse commodo risus ut tortor fringilla rhoncus. Curabitur eu risus sapien. Duis neque eros, sollicitudin nec diam non, suscipit blandit leo. Proin a nisl accumsan, facilisis eros id, porta nisl. Donec at sagittis lorem. Sed accumsan tempus purus, ut molestie ante imperdiet eu. Duis facilisis, orci commodo laoreet rutrum, diam massa pharetra mauris, quis ultricies neque elit vel tellus. Fusce tempus, sem eu posuere congue, lorem risus porta dolor, id egestas diam augue vitae nulla. Etiam faucibus ligula in ullamcorper vestibulum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas non felis et ex cursus ullamcorper eu non risus.

Nulla aliquam lectus id erat dapibus pulvinar. Nunc sapien augue, iaculis at laoreet vitae, sodales a nibh. Nam condimentum viverra diam nec lacinia. Pellentesque metus risus, pulvinar eu neque ac, interdum pharetra libero. Vestibulum iaculis turpis at arcu molestie, at aliquet sem dignissim. Ut sit amet ipsum ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque euismod elit vitae augue posuere congue. Phasellus viverra arcu vel faucibus pharetra. Nunc imperdiet pretium laoreet. Curabitur semper neque eu risus cursus laoreet.

Integer ac bibendum justo, vel eleifend quam. Quisque aliquet, felis vitae aliquet malesuada, eros augue blandit metus, quis mollis turpis sapien at eros. Duis ut sapien purus. Sed a odio dictum, efficitur magna eu, sodales odio. Aliquam turpis lacus, aliquam non tempus gravida, lobortis id dolor. Vivamus viverra finibus nisi, at bibendum sem. Donec fermentum tristique metus eget tincidunt. Aenean elementum erat vel metus laoreet aliquet. Morbi dignissim dolor sem, ut ultricies tortor suscipit sit amet. Duis a nisi imperdiet, volutpat dui ac, congue lacus. Morbi sagittis placerat sem, ac hendrerit libero maximus in.

Suspendisse mattis ut ante et semper. Aenean eu euismod nisi. Aliquam convallis laoreet nunc sed viverra. Nunc quis erat leo. Vestibulum augue felis, dignissim sit amet ullamcorper non, blandit sit amet sapien. Suspendisse in bibendum arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam posuere aliquet sollicitudin. Fusce varius vitae mi in luctus. Donec sodales augue turpis, nec laoreet erat bibendum at. Phasellus vitae ipsum luctus, rhoncus augue quis, porta sem. Etiam tempus consectetur arcu eget suscipit. Integer eu pellentesque sem, vitae maximus nisi. Phasellus fringilla est non orci pharetra maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla, lacus non auctor fermentum, dui risus ullamcorper tortor, ut placerat nibh nulla quis velit.

Aenean pharetra leo id convallis cursus. Donec tincidunt odio magna, nec venenatis risus pulvinar non. Pellentesque lacinia odio sed purus ornare, in faucibus velit euismod. Phasellus vitae congue mi. Curabitur ex metus, volutpat nec quam et, faucibus aliquam purus. Phasellus imperdiet mollis nunc, at finibus odio luctus id. Etiam et nisl vitae lorem pellentesque elementum.

Donec elementum ornare dolor, eget eleifend urna dapibus sit amet. Etiam ligula nisi, pretium facilisis mauris sit amet, ultrices aliquam ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec a congue sapien. Vestibulum scelerisque sapien eu luctus bibendum. Praesent lacinia dolor vel felis bibendum, eu fermentum magna egestas. Aenean fermentum libero ut eros sollicitudin, sed pellentesque massa placerat. Cras porta tristique tempor. Mauris sed blandit ipsum. Nullam ornare mauris vehicula, faucibus nulla nec, gravida est. Donec id tincidunt neque, molestie tincidunt urna. Mauris purus leo, tincidunt ut molestie in, ullamcorper at tortor.

Phasellus eget varius felis. Suspendisse suscipit velit quis volutpat faucibus. Nunc pellentesque aliquam dolor et sodales. Aliquam erat volutpat. Nullam ut molestie nunc, sit amet tristique nibh. Aliquam metus justo, volutpat sed mi. 
`;
